services:
  - type: web
    name: benriya-homepage
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: JDBC_URL
        value: jdbc:postgresql://dpg-d1vpr97diees73bu3bjg-a.oregon-postgres.render.com/tenohira_db
      - key: DB_USERNAME
        value: tenohira_db_user
      - key: DB_PASSWORD
        value: QiEyc7gvXMUcD0r7pdXNP6dCprD6ueU0

