services:
  - type: web
    name: benriya-homepage
    env: java
    buildCommand: "./gradlew build -x test"
    startCommand: "java -jar build/libs/homepage-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: JDBC_URL
        value: jdbc:postgresql://dpg-d1vpr97diees73bu3bjg-a.oregon-postgres.render.com/tenohira_db
      - key: DB_USERNAME
        value: tenohira_db_user
      - key: DB_PASSWORD
        value: QiEyc7gvXMUcD0r7pdXNP6dCprD6ueU0


